config/routes.rb
Rails.application.routes.draw do
  resources :ratings, only: [:create]
  resources :zombies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ApplicationRecord
  validates :name, :health, :weapon, :photo, presence: true
  validates :weapon, inclusion: { in: %w(Hax Chainsaw Hammer),
    message: "%{value} no puedes elegir esa arma" }
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    Rating.create(rating_params)
  end

  private
  def rating_params
    params.require(:rating).permit(:score, :zombie_id)
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :kills, :photo, :health, :weapon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieAttack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/ratings/create.js.erb
$('#notice').html('Calificación gardad');

app/views/zombies/_form.html.erb
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :weapon %>
    <%= form.select :weapon, options_for_select([ "Hax","Chainsaw", "Hammer"," Bazuca" ], zombie.weapon) %>
  </div>

  <div class="field">
    <%= form.label :kills %>
    <%= form.number_field :kills %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Zombies</h1>

<p id="notice"><%= notice %></p>
<% @zombies.each_slice(3) do |three_zombies| %>
      <div class="card-deck">
      <% three_zombies.each do |zombie| %>
          <div class="card">
          <%= image_tag zombie.photo, class: 'card-img-top' %>
            <div class="card-body">
              <h5 class="card-title"><%= zombie.name %></h5>
              <p class="card-text">Kills: <%= zombie.kills %></p>
              <p class="card-text">Health: <%= zombie.health %></p>
              <p class="card-text">Weapon: <%= zombie.weapon %></p>
              <%= link_to 'Show', zombie, class: 'btn btn-primary' %>
              <%= link_to 'Edit', edit_zombie_path(zombie), class: 'btn btn-warning' %>
              <%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                <h5>Califica tu Zombie</h5>
                <div class='starrr' id='star1' data-zombie='<%= zombie.id %>'></div>
                <div>&nbsp;
                <span class='your-choice-was' style='display: none;'>
                  Your rating was <span class='choice'></span>.
                </span>
                <div>avg</div>
                <span><%= (zombie.ratings.inject(0){|acc,sum| acc += sum.score} / zombie.ratings.length) if zombie.ratings.length > 0 %></span>
              <div class="card-footer">
              <small class="text-muted">Updated at: <%= time_ago_in_words zombie.updated_at %></small>
            </div>
          </div>
       <% end %>
    </div>
    <% end %>
  <br>
<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Kills:</strong>
  <%= @zombie.kills %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @zombie.photo %>
</p>

<p>
  <strong>Health:</strong>
  <%= @zombie.health %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>